
server:
  port: 9091

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass&ssl=false
      host: localhost
      port: 27017
      database: fuelstation

kafka:
  bootstrap-servers: 9092